project_id = "unjmflimsliqjnstmtrg"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-reengagement-email]
verify_jwt = false

[functions.send-goodbye-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-username-reminder]
verify_jwt = false
